### ISSUE TITLE
Checklist para versão 1.0

### ISSUE THREAD

**Issue by fmartins-andre** [ri1anapolis/ri1anapolis#4]
- [x] Incluir os textos definitivos;
- [x] Botão de voltar ao topo;
- [x] Encontrar/Produzir e incluir as imagens definitivas;
- [x] Definir o background do header;
- [x] Incluir a otimização de imagens do gatsby;
- [x] Controlar o botão voltar do navegador quando o drawer de serviços estiver aberto (para evitar sair do site quando em dispositivos móveis);
- [x] Criar e adicionar componente de avisos (modal que abre ao entrar na página) ;
- [x] Arrumar os metadados e SEO;
- [x] Compatibilizar com PWA (em avaliação)
- [ ] Definir armazenamento e distribuição dos arquivos de download e fixar link estático para cada um;
- [x] Definir dados necessários para pesquisa de protocolos
- [x] Criar backend de produção e gerar as chaves de API e inserir no sistema;
- [x] Fazer o build automatizado para o netlify;
- [x] Configurar DNS para o netlify;
